package com.example.codechallenge.model.pullRequestEvent

data class PullRequest(
    val additions: Int,
    val author_association: String,
    val changed_files: Int,
    val comments: Int,
    val comments_url: String,
    val commits: Int,
    val commits_url: String,
    val created_at: String,
    val deletions: Int,
    val diff_url: String,
    val draft: Boolean,
    val html_url: String,
    val id: Int,
    val issue_url: String,
    val locked: Boolean,
    val maintainer_can_modify: Boolean,
    val mergeable_state: String,
    val merged: Boolean,
    val node_id: String,
    val number: Int,
    val patch_url: String,
    val review_comment_url: String,
    val review_comments: Int,
    val review_comments_url: String,
    val state: String,
    val statuses_url: String,
    val title: String,
    val updated_at: String,
    val url: String,
)